Algoritmo "Meu Nome"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Curso em Vídeo
// Descrição   : Aula 3 - Atribuições  Comando de Entrada e Operadores
// Autor(a)    : Ton Queiroz
// Data atual  : 14/02/2023
Var
   N1, N2: Inteiro
   M : Real
Inicio
Escreva ("Informe um Numero: ")
Leia (N1)
Escreva ("Informe outro Numero: ")
Leia (N2)
M <- (N1+N2)/2
Escreval ("A Média entre Entre os Numeros ", N1, " e ", N2, " é Igual a ", M)

Fimalgoritmo