Algoritmo "Creuza 01"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 16/02/2023
Var
AA, AN, Idade : Inteiro

Inicio
Escreval ("Em que ano estamos?")
Leia (AA)
Escreval ("Em que ano nasci?")
Leia (AN)
Idade <- (AA-AN)
Escreval ( "Eu Tenho", Idade, " Anos.")


Fimalgoritmo