Algoritmo "Sequancia  Fibonacci"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 01/03/2023
Var
N, f1, f2, f3 : Inteiro


Inicio
n<-0
F1<-0
f2<-1
f3<-1


 Para N := 1 ate 15 passo 1 faca


       Escreva (F1)
       
       f1<- f2
       f2<- f3
       f3<-F1+f2
       


 fimpara
 


Fimalgoritmo