algoritmo "Soma Procedimentos"
var
   N : inteiro

procedimento parouimpar ( X: inteiro)
INICIO
   escreval(" o valor de n é ", n )
   escreval(" o valor de x é ", x )
   SE (X%2=1)ENTÃO
      escreval (" o numero ", x, "  é impar!")
   senao
      escreval (" o numero ", x, "  é par!")
   fimse

FIMPROCEDIMENTO


inicio
   escreval(" DIGITE UM NÚMERO " )
   LEIA (N)
   PAROUIMPAR (N)

   escreval(" o valor de n é ", n )
   escreval(" o valor de x é ", x )


Fimalgoritmo